# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9041e56c925d99d3b89336493ad79cceae7dce4526accce61913b7bc622b63fe79bc84afe7fbd0ff347a627db5cf5418a7df8c409186acdb44bbe8d6a759dc7

test:
  secret_key_base: 07d0560db3a001cd1798f3aa722f51c9c8dff18ebfff6fe2e861bc5ef0d50cc95b75329e078f15104e8f153c51884494c7e74284c75d0ac4e71325c0cc43ef11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
